baseURL       = "https://my-affi-site.pages.dev/"
languageCode  = "ja"
title         = "Genkaiブログ"
theme         = "PaperMod"

[params]
  description       = "最新のITトレンド・ガジェットレビューから美容・健康アイテムの解説とお得な比較情報をお届けするブログ"
  defaultTheme      = "auto"          # OSのダーク/ライトに追従
  ShowReadingTime   = true            # 読了時間を表示
  ShowShareButtons  = true            # SNS共有ボタン
  customCSS         = ["css/custom.css"]

# ------- ↑ params テーブルここまで ---------

[[menu.main]]      # ← params の外に置くのがポイント
  name   = "ホーム"
  url    = "/"
  weight = 1
