baseURL = "https://my-affi-site.pages.dev/"     # ← ご自身の Preview URL or 独自ドメイン
languageCode = "ja"                             # ← 日本語サイトなら "ja"
title = "Genkaiブログ"                     # ← サイト名を自由に変更
theme = "ananke"                                # ← 変更不要

# --- 以下は任意設定 ---
[params]
  description = "最新のITトレンド・ガジェットレビューから美容・健康アイテムの解説とお得な比較情報をお届けするブログ"

