baseURL       = "https://my-affi-site.pages.dev/"
languageCode  = "ja"
title         = "Genkaiブログ"
theme         = "PaperMod"

[params]
  description       = "最新のITトレンド・ガジェットレビューから美容・健康アイテムの解説とお得な比較情報をお届けするブログ"
  defaultTheme      = "auto"
  ShowReadingTime   = true
  ShowShareButtons  = true
  customCSS         = ["css/custom.css"]

  # GA を使わない場合は空文字で OK
  googleAnalytics   = ""

# ------- ↑ params テーブルここまで ---------

[[menu.main]]      # ← params の外に置くのがポイント
  name   = "ホーム"
  url    = "/"
  weight = 1


[params]
  customCSS = ["css/custom.css"]
  googleFonts = ["Noto+Sans+JP:400,700"]  # 日本語可視性に優れたフォント
